# Generated by Django 3.2.5 on 2021-09-02 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have', models.CharField(choices=[('Beshumi', 'Beshumi'), ('Ufliscixe', 'Ufliscixe'), ('Fari', 'Fari'), ('Archeviti', 'Archeviti')], max_length=50)),
                ('wants', models.CharField(choices=[('Beshumi', 'Beshumi'), ('Ufliscixe', 'Ufliscixe'), ('Fari', 'Fari'), ('Archeviti', 'Archeviti')], max_length=50)),
                ('nakad', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
