# Generated by Django 3.2.5 on 2021-09-02 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_market', '0002_auto_20210902_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='have',
            field=models.CharField(choices=[('ბეშუმი', 'ბეშუმი'), ('უფლისციხე', 'უფლისციხე'), ('ფარი', 'ფარი'), ('არჩევითი', 'არჩევითი')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='nakad_has',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='nakad_wants',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='wants',
            field=models.CharField(choices=[('ბეშუმი', 'ბეშუმი'), ('უფლისციხე', 'უფლისციხე'), ('ფარი', 'ფარი'), ('არჩევითი', 'არჩევითი')], max_length=50, null=True),
        ),
    ]
