# Generated by Django 3.2.5 on 2021-09-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_market', '0004_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offered_nakad',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_market.post'),
        ),
    ]
