# Generated by Django 3.2.5 on 2021-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_market', '0005_auto_20210903_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('აქტიური', 'აქტიური'), ('დასრულებული', 'დასრულებული')], default='აქტიური', max_length=50),
        ),
    ]
