# Generated by Django 3.2.5 on 2021-09-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_market', '0008_auto_20210906_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uni',
            field=models.CharField(choices=[('ფრიუნი', 'ფრიუნი'), ('აგრუნი', 'აგრუნი')], max_length=50, null=True),
        ),
    ]
